from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass

from pydantic import BaseModel, Field

from app.models.policy import Evidence, PolicyData
from app.services.llm_service import LLMService


class QueryAnswer(BaseModel):
    answer: str
    evidence: list[Evidence] = Field(default_factory=list, max_length=3)
    inconclusive: bool = False


class _QueryDecision(BaseModel):
    """Small schema generated by the LLM; evidence is attached deterministically."""

    answer: str
    inconclusive: bool = False


@dataclass
class _Candidate:
    text: str
    evidence: Evidence | None = None
    score: float = 0.0


class QueryAgent:
    """Answers questions over compact, relevant structured policy data.

    The LLM no longer receives the complete PolicyData JSON. A lightweight local
    retrieval step first selects only the most relevant structured items. This
    makes local inference much faster and keeps source evidence under application
    control instead of asking the LLM to reproduce it.
    """

    _STOPWORDS = {
        "a", "ao", "aos", "as", "da", "das", "de", "do", "dos", "e", "em",
        "essa", "esse", "esta", "este", "eu", "ha", "na", "nas", "no", "nos",
        "o", "os", "para", "por", "qual", "quais", "que", "se", "tem", "uma",
        "um", "qual", "quais", "como", "onde", "quando",
    }

    def __init__(self, top_k: int = 6) -> None:
        self.llm = LLMService()
        self.top_k = top_k

    def run(self, policy: PolicyData, question: str) -> QueryAnswer:
        question = question.strip()
        if not question:
            return QueryAnswer(answer="Informe uma pergunta.", inconclusive=True)

        candidates = self._build_candidates(policy)
        selected = self._retrieve(candidates, question, self.top_k)
        context = self._build_context(policy, selected)

        prompt = f"""
Responda à pergunta usando EXCLUSIVAMENTE o CONTEXTO fornecido.

REGRAS:
- Não invente informações e não use conhecimento externo.
- Se o contexto não permitir responder, diga objetivamente que a informação não foi identificada e marque inconclusive=true.
- Responda em português, de forma curta e direta, preferencialmente em até 5 linhas.
- Não repita o texto integral das evidências.
- Não dê aconselhamento jurídico.
- Retorne somente o JSON solicitado pelo schema.

PERGUNTA:
{question}

CONTEXTO:
{context}
"""

        decision = self.llm.generate_json(
            prompt,
            _QueryDecision,
            num_predict=512,
            timeout=300,
            num_ctx=4096,
        )

        evidence = self._collect_evidence(selected, max_items=3)
        return QueryAnswer(
            answer=decision.answer,
            evidence=evidence,
            inconclusive=decision.inconclusive,
        )

    def _build_candidates(self, policy: PolicyData) -> list[_Candidate]:
        candidates: list[_Candidate] = []

        for item in policy.coverages:
            ev = item.evidence
            candidates.append(
                _Candidate(
                    text=(
                        "TIPO: COBERTURA\n"
                        f"Nome: {item.name}\n"
                        f"Descrição: {item.description or 'não identificada'}\n"
                        f"Limite: {item.limit_value if item.limit_value is not None else 'não identificado'} "
                        f"{item.currency or ''}\n"
                        f"Franquia: {item.deductible_value if item.deductible_value is not None else 'não identificada'}\n"
                        f"Texto da franquia: {item.deductible_text or 'não identificado'}\n"
                        f"Fonte: {self._evidence_excerpt(ev)}"
                    ),
                    evidence=ev,
                )
            )

        for item in policy.exclusions:
            ev = item.evidence
            candidates.append(
                _Candidate(
                    text=(
                        "TIPO: EXCLUSÃO\n"
                        f"Categoria: {item.category}\n"
                        f"Descrição: {item.description}\n"
                        f"Fonte: {self._evidence_excerpt(ev)}"
                    ),
                    evidence=ev,
                )
            )

        for item in policy.special_clauses:
            ev = item.evidence
            candidates.append(
                _Candidate(
                    text=(
                        "TIPO: CLÁUSULA ESPECIAL\n"
                        f"Categoria: {item.category}\n"
                        f"Título: {item.title or 'não identificado'}\n"
                        f"Descrição: {item.description}\n"
                        f"Fonte: {self._evidence_excerpt(ev)}"
                    ),
                    evidence=ev,
                )
            )

        for observation in policy.observations:
            candidates.append(_Candidate(text=f"TIPO: OBSERVAÇÃO\n{observation}"))

        return candidates

    def _retrieve(self, candidates: list[_Candidate], question: str, top_k: int) -> list[_Candidate]:
        q_tokens = self._tokens(question)
        q_norm = self._normalize(question)

        for candidate in candidates:
            c_tokens = self._tokens(candidate.text)
            overlap = q_tokens & c_tokens
            score = float(len(overlap))

            # Reward multiword fragments from the question that appear verbatim.
            meaningful = [token for token in q_norm.split() if token not in self._STOPWORDS and len(token) > 2]
            for i in range(len(meaningful) - 1):
                phrase = f"{meaningful[i]} {meaningful[i + 1]}"
                if phrase in self._normalize(candidate.text):
                    score += 1.5

            candidate.score = score

        ranked = sorted(candidates, key=lambda item: item.score, reverse=True)
        positives = [item for item in ranked if item.score > 0]
        return positives[:top_k]

    def _build_context(self, policy: PolicyData, selected: list[_Candidate]) -> str:
        header = (
            "DADOS GERAIS DA APÓLICE\n"
            f"Documento: {policy.document_name}\n"
            f"Seguradora: {policy.insurer or 'não identificada'}\n"
            f"Número da apólice: {policy.policy_number or 'não identificado'}\n"
            f"Segurado: {policy.insured_name or 'não identificado'}\n"
            f"Produto: {policy.product or 'não identificado'}\n"
            f"Vigência inicial: {policy.effective_start or 'não identificada'}\n"
            f"Vigência final: {policy.effective_end or 'não identificada'}"
        )

        if not selected:
            return header + "\n\nNenhum item estruturado relevante foi encontrado para a pergunta."

        details = "\n\n---\n\n".join(item.text for item in selected)
        return f"{header}\n\nITENS ESTRUTURADOS RELEVANTES\n{details}"

    @staticmethod
    def _collect_evidence(selected: list[_Candidate], max_items: int) -> list[Evidence]:
        result: list[Evidence] = []
        seen: set[tuple[int | None, str]] = set()
        for candidate in selected:
            ev = candidate.evidence
            if ev is None or not ev.text.strip():
                continue
            key = (ev.page, ev.text.strip())
            if key in seen:
                continue
            seen.add(key)
            result.append(ev)
            if len(result) >= max_items:
                break
        return result

    @staticmethod
    def _evidence_excerpt(evidence: Evidence | None, limit: int = 700) -> str:
        if evidence is None or not evidence.text.strip():
            return "não identificada"
        text = " ".join(evidence.text.split())
        if len(text) > limit:
            text = text[:limit].rstrip() + "…"
        page = evidence.page if evidence.page is not None else "-"
        return f"página {page}: {text}"

    @classmethod
    def _tokens(cls, value: str) -> set[str]:
        return {
            token
            for token in re.findall(r"[a-z0-9]+", cls._normalize(value))
            if len(token) > 2 and token not in cls._STOPWORDS
        }

    @staticmethod
    def _normalize(value: str) -> str:
        value = unicodedata.normalize("NFKD", value.lower())
        return "".join(ch for ch in value if not unicodedata.combining(ch))
